project:
  name: quickstart-amazon-eks
  owner: quickstart-eng@amazon.com
  regions:
  - me-south-1
  template: templates/amazon-eks-entrypoint-new-vpc.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
  public-endpoint:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
    regions:
      - ap-northeast-2
  cluster-autoscaler:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - eu-central-1
  efs-prov:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EfsStorageClass: Enabled
      ClusterAutoScaler: Disabled
      EfsThroughputMode: provisioned
      EfsProvisionedThroughputInMibps: 100
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - ap-east-1
  managed-node-group:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Disabled
      EKSPublicAccessEndpoint: Enabled
    regions:
    - ap-south-1
  monitoring-prom-graf:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      MonitoringStack: Prometheus + Grafana
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - ap-southeast-2
  2az:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - ca-central-1
    - cn-north-1
    - cn-northwest-1
  no-logging:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: "2"
      EKSClusterLoggingTypes: ""
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - eu-west-2
  with-hybrid:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - us-west-2
  alb-ingress:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ALBIngressController: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - us-east-2
  fargate:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      FargateNamespaces: kube-system
      FargateLabels: 'app.kubernetes.io/name=aws-cluster-autoscaler'
      EKSPublicAccessEndpoint: Enabled
      NodeGroupType: 'Unmanaged'
    regions:
    - us-east-1
  enable-oidc:
    regions:
      - eu-west-1
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      IamOidcProvider: Enabled
      EKSPublicAccessEndpoint: Enabled
      NodeGroupOS: Bottlerocket
      NodeInstanceFamily: ARM
      NodeInstanceType: c6g.medium
      NodeGroupType: 'Unmanaged'
  snyk:
    regions:
      - eu-west-3
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      SnykIntegration: Enabled
      SnykIntegrationId: ---overridden---
  new-relic:
    regions:
      - sa-east-1
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSPublicAccessEndpoint: Enabled
      NewRelicIntegration: Enabled
      NewRelicLicenseKey: ---overridden---
  managed-node-group-ASC:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      ClusterAutoScaler: Enabled
      TestSuite: Enabled
    regions:
    - af-south-1
  windows:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      TestSuite: Enabled
      NodeGroupOS: Windows
      NodeGroupType: 'Unmanaged'
    regions:
    - eu-north-1
